services:
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]   # enable JetStream
    ports:
      - "4222:4222"     # client connections
      - "8222:8222"     # monitoring/HTTP endpoint
    volumes:
      - nats_data:/data   # persist data for JetStream



  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ingestionworker
      POSTGRES_PASSWORD: ingestionworker
      POSTGRES_DB: secureflow_events
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  nats_data:
  postgres-data: